### ISSUE TITLE
StoreOnce G3 zabbix monitoring templates

### ISSUE THREAD

**Issue by KavyaKanya** [HewlettPackard/python-storage-clients#30]
Hello Ivan

Any suggested way to monitor the HPE Store Once Storage device in Zabbix

Could you help me out with any exisitng teamplates and scripts via which monitoring the Storage device could be established

**Comment by IvanVSmirnov** [comment]
Hi,
What metrics do you want to see in zabbix?

**Comment by KavyaKanya** [comment]
Hello Ivan

Please find the below Metrics we'd need to monitor

I/O operations
Bandwidth
Latency
Storage utilization
Object storage daemon (OSD) status(how many IN or UP)
Number of monitors (mons) and OSDs
Number of pools and placement groups
Overall Ceph status

**Comment by IvanVSmirnov** [comment]
Looks like this list was copied from another object storage, some metrics are not applicable to StoreOnce.

This repository contains general purpose RestAPI clients for storage systems. There are no plans to extend this library with client applications like a zabbix monitoring script. It is not a good place for such scripts.

I know that many people use this library to get data for zabbix and nagios. I think a separate repo could be created for this script. But most importantly, we need people who are ready to actively participate in testing and development.

Let's leave this topic open for a couple of months for discussion.

**Comment by IvanVSmirnov** [comment]
Tool to monitoring storage systems: [stor2rrd.com](https://stor2rrd.com/support_matrix.php)
